### ISSUE TITLE
Valid config HomeAssistant fault

### ISSUE THREAD

**Issue by MikkelLindChr** [martonborzak/beoplay-custom-component#4]
Platform error media_player.beoplay - cannot import name 'CancelledError' from 'asyncio.futures' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py)
Platform error media_player.beoplay - cannot import name 'CancelledError' from 'asyncio.futures' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py)

**Comment by martonborzak** [comment]
What Home Assistant version are you running?

I haven't tested it with python 3.8, but I will try to install it and check up on it.

**Comment by MikkelLindChr** [comment]
Thanks :)

Den 12. nov. 2019 kl. 20.02 skrev Marton <notifications@github.com<mailto:notifications@github.com>>:


What Home Assistant version are you running?

I haven't tested it with python 3.8, but I will try to install it and check up on it.

**Comment by MikkelLindChr** [comment]
arch | x86_64
-- | --
dev | true
docker | false
hassio | false
os_name | Darwin
os_version | 10.15.1
python_version | 3.8.0
timezone | Europe/Copenhagen
version | 0.102.0.dev0
virtualenv | false

**Comment by akachrmol** [comment]
Hi,
I have the same problem after upgrading from Python 3.7 to 3.8
